# Generated by Django 6.0.7 on 2026-07-29 08:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('problem_description', models.TextField(help_text="Patient's own words describing the issue.")),
                ('urgency', models.CharField(choices=[('low', 'Mild — can wait a few days'), ('medium', 'Moderate — would like to see someone soon'), ('high', 'Severe — need to see someone urgently')], max_length=10)),
                ('duration', models.CharField(choices=[('just_started', 'Just started (today)'), ('few_days', 'A few days'), ('week_plus', 'A week or more'), ('chronic', 'Ongoing / recurring')], max_length=20)),
                ('patient_type', models.CharField(choices=[('new', 'New Patient'), ('existing', 'Existing Patient')], max_length=10)),
                ('preferred_time', models.CharField(blank=True, help_text="Free text, e.g. 'weekday evenings'.", max_length=100)),
                ('age_group', models.CharField(blank=True, choices=[('child', 'Child (under 12)'), ('teen', 'Teen (12-19)'), ('adult', 'Adult (20-59)'), ('senior', 'Senior (60+)')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('language_preference', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(blank=True, help_text='0-1 keyword-match confidence from the classifier. Not a medical score.', null=True)),
                ('ai_notes', models.TextField(blank=True, help_text='Internal notes from the classifier for the clinic/ops team.')),
                ('lead_created', models.BooleanField(default=False)),
                ('source_channel', models.CharField(choices=[('web_chat', 'Website'), ('whatsapp', 'WhatsApp'), ('voice', 'Voice')], default='web_chat', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_clinics', models.ManyToManyField(blank=True, related_name='intake_matches', to='clinics.clinic')),
                ('preferred_locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sessions', to='locations.locality')),
                ('problem_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_sessions', to='clinics.problem')),
                ('selected_clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_selections', to='clinics.clinic')),
                ('suggested_treatments', models.ManyToManyField(blank=True, related_name='intake_sessions', to='clinics.treatment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
