# Generated by Django 6.0.7 on 2026-07-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='problems',
            field=models.ManyToManyField(blank=True, related_name='blog_categories', to='clinics.problem'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='treatments',
            field=models.ManyToManyField(blank=True, related_name='blog_categories', to='clinics.treatment'),
        ),
    ]
