# Generated by Django 6.0.7 on 2026-07-29 06:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='e.g. tooth-pain', max_length=180, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('symptom_explanation', models.TextField(blank=True)),
                ('possible_causes', models.TextField(blank=True)),
                ('when_urgent_care_needed', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='e.g. dr-sharma-dental-care-roorkee', max_length=220, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('map_embed_url', models.URLField(blank=True, help_text='Google Maps embed URL placeholder')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone_number', models.CharField(help_text='Local format for display, e.g. 01332-123456', max_length=20)),
                ('whatsapp_number', models.CharField(help_text="International format without '+' for wa.me links, e.g. 919876543210", max_length=20)),
                ('timings', models.CharField(help_text='e.g. Mon-Sat 9:00 AM - 7:00 PM', max_length=200)),
                ('consultation_fee', models.PositiveIntegerField(blank=True, help_text='INR, optional', null=True)),
                ('about', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinics/logos/')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='clinics/covers/')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='locations.city')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinics', to='locations.locality')),
                ('problems', models.ManyToManyField(blank=True, related_name='clinics', to='clinics.problem')),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('qualification', models.CharField(help_text='e.g. BDS, MDS (Orthodontics)', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='dentists/photos/')),
                ('is_primary', models.BooleanField(default=False, help_text='Primary dentist shown on clinic profile.')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentists', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='1-5')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(help_text='e.g. root-canal', max_length=180, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('explanation', models.TextField(blank=True, help_text='Simple explanation of the treatment.')),
                ('symptoms', models.TextField(blank=True, help_text='Symptoms that suggest this treatment is needed.')),
                ('when_to_visit', models.TextField(blank=True)),
                ('what_to_expect', models.TextField(blank=True)),
                ('fee_range_min', models.PositiveIntegerField(blank=True, help_text='Estimated fee, INR', null=True)),
                ('fee_range_max', models.PositiveIntegerField(blank=True, help_text='Estimated fee, INR', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_problems', models.ManyToManyField(blank=True, related_name='related_treatments', to='clinics.problem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='problem',
            name='suggested_treatment_categories',
            field=models.ManyToManyField(blank=True, related_name='suggested_for_problems', to='clinics.treatment'),
        ),
        migrations.CreateModel(
            name='ClinicFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='locations.city')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='clinics.clinic')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='locations.locality')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='clinics.problem')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='clinics.treatment')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='treatments',
            field=models.ManyToManyField(blank=True, related_name='clinics', to='clinics.treatment'),
        ),
        migrations.CreateModel(
            name='VerificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_source', models.CharField(choices=[('phone_call', 'Phone Call'), ('whatsapp', 'WhatsApp'), ('google_profile', 'Google Business Profile'), ('website', 'Clinic Website'), ('in_person', 'In Person Visit'), ('other', 'Other')], default='phone_call', max_length=20)),
                ('last_verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('proof_website', models.URLField(blank=True)),
                ('proof_google_profile', models.URLField(blank=True)),
                ('phone_confirmed', models.BooleanField(default=False)),
                ('timings_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_records', to='clinics.clinic')),
            ],
            options={
                'ordering': ['-last_verified_at'],
            },
        ),
    ]
