# Generated by Django 6.0.7 on 2026-07-29 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_treatment_problem_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clinics/gallery/')),
                ('caption', models.CharField(blank=True, max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='clinics.clinic')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
