# Generated by Django 6.0.7 on 2026-07-29 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cta_type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('call', 'Call')], max_length=10)),
                ('page_source', models.CharField(choices=[('home', 'Home'), ('city', 'City Page'), ('locality', 'Locality Page'), ('clinic', 'Clinic Profile'), ('treatment', 'Treatment Page'), ('problem', 'Problem Page'), ('blog', 'Blog')], max_length=20)),
                ('referrer_url', models.URLField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='locations.city')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='clinics.clinic')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='locations.locality')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clinics.problem')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='clinics.treatment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinic', 'created_at'], name='leads_lead_clinic__3ae893_idx'), models.Index(fields=['page_source', 'created_at'], name='leads_lead_page_so_f9f340_idx')],
            },
        ),
    ]
