# Generated by Django 6.0.7 on 2026-07-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('leads', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='cta_label',
            field=models.CharField(blank=True, help_text="Button text/context, e.g. 'WhatsApp Now'.", max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='page_slug',
            field=models.CharField(blank=True, help_text='Slug of the page the click originated from, e.g. the treatment or clinic slug.', max_length=220),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='referrer_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['page_source', 'page_slug', 'created_at'], name='leads_lead_page_so_5820c3_idx'),
        ),
    ]
