# Generated by Django 6.0.7 on 2026-07-29 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('clinics', '0001_initial'),
        ('intake', '0001_initial'),
        ('leads', '0002_lead_cta_label_lead_page_slug_lead_utm_campaign_and_more'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_changed', 'Status Changed'), ('follow_up_set', 'Follow-up Set'), ('assigned', 'Assigned'), ('note_added', 'Note Added'), ('contacted', 'Marked Contacted')], max_length=20)),
                ('from_value', models.CharField(blank=True, max_length=100)),
                ('to_value', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Lead activity log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='accounts.clinicuser'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Captured from intake, if provided.', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='follow_up_type',
            field=models.CharField(choices=[('none', 'No Follow-up Needed'), ('today', 'Follow Up Today'), ('tomorrow', 'Follow Up Tomorrow'), ('later', 'Follow Up Later')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='intake_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='intake.intakesession'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='message',
            field=models.TextField(blank=True, help_text='Free-text message captured from intake, if provided.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='missed_reason',
            field=models.CharField(blank=True, help_text="e.g. 'Patient did not answer', 'Clinic did not respond in time'.", max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Appointment Scheduled'), ('visited', 'Visited'), ('closed', 'Closed'), ('not_reachable', 'Not Reachable'), ('missed', 'Missed')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='page_source',
            field=models.CharField(choices=[('home', 'Home'), ('city', 'City Page'), ('locality', 'Locality Page'), ('clinic', 'Clinic Profile'), ('treatment', 'Treatment Page'), ('problem', 'Problem Page'), ('blog', 'Blog'), ('intake', 'AI Intake')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['clinic', 'status'], name='leads_lead_clinic__40c21f_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['clinic', 'follow_up_date'], name='leads_lead_clinic__0cc53e_idx'),
        ),
        migrations.AddField(
            model_name='leadactivitylog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_entries', to='accounts.clinicuser'),
        ),
        migrations.AddField(
            model_name='leadactivitylog',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='accounts.clinicuser'),
        ),
        migrations.AddField(
            model_name='leadnote',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead'),
        ),
    ]
