# Generated by Django 6.0.7 on 2026-07-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('city', 'City Page'), ('locality', 'Locality Page'), ('clinic', 'Clinic Profile'), ('treatment', 'Treatment Page'), ('problem', 'Problem Page'), ('blog', 'Blog')], max_length=20)),
                ('page_slug', models.CharField(blank=True, max_length=220)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('referrer', models.CharField(blank=True, max_length=300)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='locations.city')),
                ('clinic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='clinics.clinic')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='locations.locality')),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='clinics.problem')),
                ('treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='clinics.treatment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['page_type', 'page_slug', 'created_at'], name='analytics_p_page_ty_efc54b_idx'), models.Index(fields=['created_at'], name='analytics_p_created_4c2b45_idx')],
            },
        ),
    ]
